### ISSUE TITLE
Error on running download_data.sh

### ISSUE THREAD

**Issue by IamAdiSri** [microsoft/GLUECoS#38]
Hi, I'm getting the following errors on running the first script, `download_data.sh`
```
ICON_POS.zip                  100%[=================================================>] 588.98K   436KB/s    in 1.3s
Traceback (most recent call last):
  File "/scratch/aditya.srivastava/GLUECoS/Data/Preprocess_Scripts/preprocess_lid_en_hi.py", line 192, in <module>
    main()
  File "/scratch/aditya.srivastava/GLUECoS/Data/Preprocess_Scripts/preprocess_lid_en_hi.py", line 175, in main
    make_temp_file(original_path)
  File "/scratch/aditya.srivastava/GLUECoS/Data/Preprocess_Scripts/preprocess_lid_en_hi.py", line 11, in make_temp_file
    shutil.copy(original_path_validation,new_path_validation)
  File "/home/aditya.srivastava/opt/Python-3.8.2/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/aditya.srivastava/opt/Python-3.8.2/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/aditya.srivastava/GLUECoS/Data/Original_Data/LID_EN_HI/temp//HindiEnglish_FIRE2013_AnnotatedDev.txt'
Downloaded LID EN HI
annotatedData.csv             100%[=================================================>]   1.52M  --.-KB/s    in 0.1s
```
Can someone help me resolve this?

**Comment by IamAdiSri** [comment]
Resolved; there were just some proxy issues.
