### ISSUE TITLE
transliterator error on running " ./download_data.sh SUBSCRIPTION_KEY" due to error in response from the specified url

### ISSUE THREAD

**Issue by BarahFazili** [microsoft/GLUECoS#48]
```
Traceback (most recent call last):
  File "transliterator.py", line 88, in <module>
    main()
  File "transliterator.py", line 79, in main
    trans = get_transliteration(vocab, headers)
  File "transliterator.py", line 38, in get_transliteration
    trans.update({body[j]['text']:i['text']})
TypeError: string indices must be integers
```

**Comment by BarahFazili** [comment]
was due to invalid subscription key.
